name: hisabkitab_mobile
description: A premium mobile app for HisabKitab.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  google_fonts: ^6.1.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  font_awesome_flutter: ^10.5.0
  animate_do: ^3.0.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
